config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "articles#home"
  get "/accueil", to: "articles#home"
  resources :profiles
end
##
##root GET    /                                                                                                 articles#index
##articles GET    /articles(.:format)                                                                               articles#index
##         POST   /articles(.:format)                                                                               articles#create
##new_article GET    /articles/new(.:format)                                                                           articles#new
##edit_article GET    /articles/:id/edit(.:format)                                                                      articles#edit
## article GET    /articles/:id(.:format)                                                                           articles#show
##         PATCH  /articles/:id(.:format)                                                                           articles#update
##         PUT    /articles/:id(.:format)                                                                           articles#update
##         DELETE /articles/:id(.:format)                                                                           articles#destroy
##profiles GET    /profiles(.:format)                                                                               profiles#index
##         POST   /profiles(.:format)                                                                               profiles#create
##new_profile GET    /profiles/new(.:format)                                                                           profiles#new
##edit_profile GET    /profiles/:id/edit(.:format)                                                                      profiles#edit
## profile GET    /profiles/:id(.:format)                                                                           profiles#show
##         PATCH  /profiles/:id(.:format)                                                                           profiles#update
##         PUT    /profiles/:id(.:format)                                                                           profiles#update
##         DELETE /profiles/:id(.:format)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def home
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    logger.info "GET..."
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to profile_path(@profile), :notice => "User successfully added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to profile_path(@profile), :notice => "User successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    logger.info "Processing the request..."
    redirect_to profiles_path, status: :see_other
  end

  private

  def profile_params
    params.require(:profile).permit(:prenom, :nom, :adresse, :age, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/articles/home.html.erb
<div class="m-2">
<h1>Projet Ruby On Rails </h1>
<h3>- Par Morgan HUE</h3>
<nav class="nav flex-column">
  <a class="nav-link active" href="/articles">Partie Article</a>
  <a class="nav-link active" href="/profiles">Partie Profile</a>
  <a class="nav-link active" href="https://gitlab.com/MorganHue/ruby-project">Lien Gitlab</a>
</nav>
<p style="font-size:15px;color:#e2e2e27a">Plus jamais je fais du rails</p>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "Nouvelle Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet - Morgan HUE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_with model: @profile, :html => { :class => "p-5" } do |form| %>
<h1>Modifier ce Profil</h1>
<div class="row mb-2">
  <div class="col form-group" >
    <%= form.label :nom %><br>
    <%= form.text_field :nom, class: "form-control" %>
  </div>
    <div class="col form-group">
    <%= form.label :prenom %><br>
    <%= form.text_field :prenom, class: "form-control" %>
  </div>
</div>


  <div class="form-group mb-2" >
    <%= form.label :adresse %><br>
    <%= form.text_area :adresse, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :photo %><br>
    <%= form.text_field :photo, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :age %><br>
    <%= form.number_field :age, in: 1..120, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Enregistrer les modifications", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<!--<ul>
  <% @profiles.each do |p| %>
    <li>
     <a href="/profiles/<%= p.id %>">
      <%= p.nom %> <%= p.prenom %>
      </a>
    </li>
  <% end %>
</ul>-->
 <div class="row">
<% @profiles.each do |p| %>
<div class="card col-4" style="max-height:30rem">
  <img class="card-img-top" src="<%= p.photo %>" alt="Photo Profile" style="max-width: 18rem;max-height:20rem">
  <div class="card-body">
    <h5 class="card-title"><%= p.nom %> <%= p.prenom %></h5>
    <p class="card-text"><%= p.adresse %></p>
    <a href="/profiles/<%= p.id %>" class="btn btn-primary">Consulter</a>
  </div>
</div>
<% end %>
</div>
<a href="/profiles/new">
<button class="btn btn-primary mt-1">Nouveau Profile</button>
</a>
<!--<%= link_to "Nouveau Profile", new_profile_path %>-->

app/views/profiles/new.html.erb
<%= form_with model: @profile, :html => { :class => "p-5" } do |form| %>
<h1>Nouveau Profil</h1>
<div class="row mb-2">
  <div class="col form-group">
    <%= form.label :nom %><br>
    <%= form.text_field :nom, class: "form-control" %>
  </div>
    <div class="col form-group">
    <%= form.label :prenom %><br>
    <%= form.text_field :prenom, class: "form-control" %>
  </div>
</div>
  <div class="form-group mb-2">
    <%= form.label :adresse %><br>
    <%= form.text_area :adresse, class: "form-control" %><br>
  </div>

  <div class="form-group mb-2">
    <%= form.label :photo %><br>
    <%= form.text_field :photo, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :age %><br>
    <%= form.number_field :age, in: 1..120, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Enregistrer le nouveau profil", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="card" style="max-width: 30rem;">
  <img class="card-img-top" src='<%= @profile.photo %>' alt="Photo du Profil">
  <div class="card-body">
    <h5 class="card-title"><%= @profile.nom %> <%= @profile.prenom %></h5>
    <p class="card-text">Adresse: <%= @profile.adresse %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Age: <%= @profile.age %> ans</li>
  </ul>
  <div class="card-body">
    <%= link_to "Mettre à jour", edit_profile_path(@profile), class: "card-link" %>
    <%= link_to "Supprimer", @profile, data: {
                                         turbo_method: :delete,
                                         turbo_confirm: "Etes-vous sûr de vouloir supprimer ce profil ?",
                                       }, method: :delete, class: "card-link" %>
  </div>
</div>